### ISSUE TITLE
how to add inline editor for multiple html elements with same class name

### ISSUE THREAD

**Issue by pandurangappa** [ckeditor/ckeditor5-build-inline#11]
InlineEditor
      .create( document.querySelectorAll( '.editor' ) )
      .then( editor => {
        console.log( editor );
      } )
      .catch( error => {
        console.error( error );
      } );

**Comment by pandurangappa** [comment]
The above code not working in Angular4 .ts file

**Comment by oleq** [comment]
The `create()` method does not support multiple elements ATM. You should loop over the elements instead

```js
for ( const el of document.querySelectorAll( '.editor' ) ) {
    InlineEditor
        .create( el )
        .then( editor => {
            console.log( 'Created', editor, 'from', el );
        } )
        .catch( error => {
            console.error( error );
        } );
}
```

**Comment by Mgsy** [comment]
Closing it due to a lack of activity.
