### ISSUE TITLE
angular project

### ISSUE THREAD

**Issue by guypeled1** [ckeditor/ckeditor5-build-inline#17]
Hi,
how can i install the editor in angular project?
for some reason it doesn't work

**Comment by ma2ciek** [comment]
Hi,

please use the https://github.com/ckeditor/ckeditor5-angular package, which integrates CKEditor 5 and Angular, guides are available here: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html

**Comment by guypeled1** [comment]
the documentation is for the editor. 
how can i install the inline editor for angular?
